params = {'r1': {'kernel_0':(9,9),
                 'output_0':16,
                 'kernel_1':(7,7),
                 'output_1':32,
                 'kernel_2':(7,7),
                 'output_2':16,
                 'kernel_3':(7,7),
                 'output_3':8,
                 'kernel_4':(1,1),
                 'output_4':1,
                 },
          'r2': {'kernel_0':(7,7),
                  'output_0':20,
                  'kernel_1':(5,5),
                  'output_1':40,
                  'kernel_2':(5,5),
                  'output_2':20,
                  'kernel_3':(5,5),
                  'output_3':10,
                  'kernel_4':(1,1),
                  'output_4':1,
                 },
          'r3': {'kernel_0':(5,5),
                 'output_0':24,
                 'kernel_1':(3,3),
                 'output_1':48,
                 'kernel_2':(3,3),
                 'output_2':24,
                 'kernel_3':(3,3),
                 'output_3':12,
                 'kernel_4':(1,1),
                 'output_4':1,
                }
        }
